### ISSUE TITLE
Can I use it between multiprocessing? 

### ISSUE THREAD

**Issue by miseon119** [joeltok/py-event-bus#1]
Hi, I have two questions:
1. Can I use it between multi processes? like one process emits event and another process listen it.
2. Can I emit event which is user defined class object nor string, int, and so on ?

Thank you.

**Comment by joeltok** [comment]
Hi, 

1. Seems like multi-processing should be possible to achieve with some modifications. 
2. With this approach you should be able to emit any kind of data type. 

Cheers.

**Comment by miseon119** [comment]
Thanks for your comment.

Would you mind give me any suggestions about which part should I modify?

```python
import asyncio
    
class EventBus():
  def __init__(self):
    self.listeners = {}

  def add_listener(self, event_name, listener):
    if not self.listeners.get(event_name, None):
      self.listeners[event_name] = {listener}
    else:
      self.listeners[event_name].add(listener)

  def remove_listener(self, event_name, listener):
    self.listeners[event_name].remove(listener)
    if len(self.listeners[event_name]) == 0:
      del self.listeners[event_name]

  def emit(self, event_name, event):
    listeners = self.listeners.get(event_name, [])
    for listener in listeners:
      asyncio.create_task(listener(event))
```
Should I modify only the `emit()` method or all of them?
