### ISSUE TITLE
Trying to use this to emit between modules

### ISSUE THREAD

**Issue by draeder** [joeltok/py-event-bus#2]
I'm basing an EventEmitter on your approach .  I created a package I'm calling `EventEmitter` with a singleton class called `Events`. I'm trying to emit and listen to events between two different modules that use this package. But what I've found is each instance of the class, even though the class is a singleton, is running on its own thread. Because of that, I'm not able to emit from one module and get the event on the listener in the other.

Do you have any thoughts about how I can get this to work?

(Note: I'm relatively new to python, so I might not be aware of some other python way to do what I'm attempting)

### EventEmitter:
```python
import asyncio


class Events:
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(Events, cls).__new__(cls)
        return cls._instance

    def __init__(self):
        self.listeners = {}

    def on(self, event_name, listener):
        if not self.listeners.get(event_name, None):
            self.listeners[event_name] = {listener}
        else:
            self.listeners[event_name].add(listener)

    def off(self, event_name, listener):
        self.listeners[event_name].remove(listener)
        if len(self.listeners[event_name]) == 0:
            del self.listeners[event_name]

    def emit(self, event_name, event):
        listeners = self.listeners.get(event_name, [])
        for listener in listeners:
            asyncio.create_task(listener(event))

```

### Emitter
```python
import time

from Drivers.Events import EventEmitter

em = EventEmitter.Events()
print(em)


while True:
    em.emit("hi", "hello")
    time.sleep(5)
```

### Listener
```python
from Drivers.Events import EventEmitter
import asyncio

em = EventEmitter.Events()
print(em)


async def received(message, *args, **kwargs):
    print(message)
    return message

while True:
    em.on("hi", received)

```

**Comment by joeltok** [comment]
Hi @draeder, I don't see any threading being done in your example code.

But one thing I can see that might be a problem is that the example you provide isn't a singleton. In both Emitter and Listener, you instantiate a separate `EventEmitter` instance, which means that emitting an event in one will not result in a reception of that event in the other. 

Try something like the following instead:

### EventEmitter.py
```py
class Events
#   ... your class code ...

em = Events()
```

### Usage
```py
fromEventEmitter import em
```

**Comment by draeder** [comment]
@joeltok Thanks - I ended up writing my own EventEmitter, which helped me understand some of the concepts you describe.
